export const STORE_CONTRACT_ADDRESS = process.env.NEXT_PUBLIC_STORE_CONTRACT;
export const SELLER_VERIF_CONTRACT_ADDRESS = process.env.NEXT_PUBLIC_SELLER_VERIF_CONTRACT;
export const VERIFIER_CONTRACT_ADDRESS = process.env.NEXT_PUBLIC_VERIFIER_CONTRACT;
export const DIGEST = process.env.DIGEST;
export const SECRET_KEY = process.env.SECRET_KEY;
export const WEB3_STORAGE_TOKEN = process.env.NEXT_PUBLIC_WEB3_STORAGE_TOKEN;
export const USDC_ADDRESS = process.env.NEXT_PUBLIC_USDC_CONTRACT;
export const USDC_MULTIPLIER = 1e6;
